### ISSUE TITLE
# Local addition

### ISSUE THREAD

**Issue by roberto-arista** [jenskutilek/RFUnicodeInfo#1]
Hey Jens,
thanks for the tool : )

What do you mean for "#Local addition:"?
`	# Local additions:
	'CR': 0x000d,
	'NULL': 0x0000,
	'fi': 0xfb01,
	'fl': 0xfb02,
	'onesuperior': 0x00b9,
	'threesuperior': 0x00b3,
	'twosuperior': 0x00b2,`

Are these glyphs part of aglfn?

**Comment by jenskutilek** [comment]
Good catch! I added these to the AGLFN module when I working on a font following FontShop’s guidelines and forgot about them. They were in an older version of AGLFN as far as I know.

I will remove them again so the file follows ‘pure’ current AGLFN names.

**Comment by roberto-arista** [comment]
🎉🎉🎉

**Comment by roberto-arista** [comment]
I assume I should get an update request from Mechanic, right?

**Comment by jenskutilek** [comment]
Fixed in 27e9ce9. Yes, the update should show up in Mechanic soon.
