### ISSUE TITLE
The 'Show Block' button doesn't actually show all glyphs from a block. 

### ISSUE THREAD

**Issue by Apochrosi** [jenskutilek/RFUnicodeInfo#4]
When using the Show block button to show or add missing entries for a block some glyphs are missing. When choosing the latin supplement 1 block I expect to see all of its 96 glyphs or codepoints shown. Instead only 91 of the 96 show up. One could understand how 00A0/nonbreakingspace wouldn't be shown but characters such as 00B9/onesuperior should absolutely be shown. The same issue can be seen in the Runic block where the last 6 reserved glyphs aren't added to the program and shown as part of the block.

I would thus like to see an option in the program for the show block button to show all characters from a given block even if they are control characters or reserved characters. Having to manually add all the missing glyphs kind of defeats the function of that feature.

**Comment by jenskutilek** [comment]
Sorry, I didn't see this earlier. I have changed the logic so that all codepoints are shown, even reserved ones. I might make that optional later.
